---@meta pandoc-types-module-core
-- The top-level `pandoc` constructors table and the format-list type used by `pandoc.read`.
--
-- Part of the split pandoc-types LuaLS annotation set. Files in this set
-- cross-reference each other's types freely -- LuaLS resolves @class/@alias
-- names across ALL files in the same library folder, so file boundaries here
-- are purely organizational and carry no functional meaning.

---@class (exact) pandoc
---@field AlignCenter Alignment
---@field AlignDefault Alignment
---@field AlignLeft Alignment
---@field AlignRight Alignment
---@field Attr fun(identifier?: string, classes?: string[], attributes?: table<string,string>): Attr `Attr` constructor.
---@field AuthorInText CitationMode
---@field Block table The `Block` constructor table. `pandoc.Block.constructor` enumerates every Block type, which is the documented way to iterate them.
---@field BlockQuote fun(content: BlocksLike): BlockQuote `BlockQuote` constructor.
---@field Blocks fun(blocks: Block|Block[]): Blocks Creates a `Blocks` list. Accepts either a single `Block` or a list of blocks; the parameter is required (calling with no arguments errors at runtime).
---@field BulletList fun(items: List<BlocksLike>|BlocksLike[]): BulletList `BulletList` constructor.
---@field Caption fun(long?: BlocksLike, short?: InlinesLike): Caption  -- `Caption` constructor.
---@field Cell fun(content: BlocksLike, align?: Alignment, row_span?: integer, col_span?: integer, attr?: Attr): Cell `Cell` (of `Table`) constructor. All parameters after `content` are optional.
---@field Citation fun(id: string, mode?: CitationMode, prefix?: InlinesLike, suffix?: InlinesLike, note_num?: integer, hash?: integer): Citation `Citation` constructor.
---@field Cite fun(content: InlinesLike, citations: List<Citation>|Citation[]): Cite `Cite` constructor.
---@field cli PandocCliModule
---@field Code fun(text: string, attr?: Attr): Code `Code` constructor.
---@field CodeBlock fun(text: string, attr?: Attr): CodeBlock `CodeBlock` constructor.
---@field Decimal ListNumberStyle
---@field DefaultDelim ListNumberDelim
---@field DefaultStyle ListNumberStyle
---@field DefinitionList fun(content: List<DefinitionListItem>|DefinitionListItem[]): DefinitionList `DefinitionList` constructor.
---@field DisplayMath MathType
---@field Div fun(content: BlocksLike, attr?: Attr): Div `Div` constructor.
---@field DoubleQuote QuoteType
---@field Emph fun(content: InlinesLike): Emph `Emph` constructor.
---@field Example ListNumberStyle
---@field Figure fun(content: BlocksLike, caption?: Caption, attr?: Attr): Figure `Figure` constructor.
---@field format PandocFormatModule
---@field Header fun(level: integer, content: InlinesLike, attr?: Attr): Header `Header` constructor.
---@field HorizontalRule fun(): HorizontalRule `HorizontalRule` constructor.
---@field Image fun(caption: InlinesLike|Inline[], src: string, title?: string, attr?: Attr): Image `Image` constructor.
---@field Inline table The `Inline` constructor table. `pandoc.Inline.constructor` enumerates every Inline type.
---@field InlineMath MathType
---@field Inlines fun(inlines: Inline|Inline[]|string): Inlines Creates an `Inlines` list. Accepts a single `Inline`, a list of inlines, or a plain string (converted to `Str`/`Space` inlines); the parameter is required (calling with no arguments errors at runtime).
---@field json PandocJsonModule
---@field layout PandocLayoutModule
---@field LineBlock fun(content: List<InlinesLike>|InlinesLike[]): LineBlock `LineBlock` constructor.
---@field LineBreak fun(): LineBreak `LineBreak` constructor.
---@field Link fun(content: InlinesLike|Inline[], target: string, title?: string, attr?: Attr): Link `Link` constructor.
---@field List fun(items?: table): List<any> `List` constructor. Returns `List<any>` rather than the bare `List`: an unparameterised return left the result's element type unresolved, so `list:insert(v)` could resolve against an unrelated `insert` field elsewhere in the library and report a missing argument.
---@field ListAttributes fun(start?: integer, style?: ListNumberStyle, delimiter?: ListNumberDelim): ListAttributes `ListAttributes` constructor.
---@field log PandocLogModule
---@field LowerAlpha ListNumberStyle
---@field LowerRoman ListNumberStyle
---@field Math fun(mathtype: MathType, text: string): Math `Math` constructor. Both parameters are required; `pandoc.Math("InlineMath")` errors at runtime.
---@field mediabag PandocMediabagModule
---@field Meta fun(meta_maps: table<string, MetaValue>): Meta `Meta` object constructor.
---@field MetaBlocks fun(blocks: BlocksLike): Blocks `MetaBlocks` constructor.
---@field MetaBool fun(bool: boolean): boolean `MetaBool` constructor (returns native boolean).
---@field MetaInlines fun(inlines: InlinesLike): Inlines `MetaInlines` constructor.
---@field MetaList fun(meta_values: List<MetaValue>|MetaValue[]): List<MetaValue> `MetaList` constructor.
---@field MetaMap fun(key_value_map: table<string, MetaValue>): MetaMap `MetaMap` constructor.
---@field MetaString fun(str: string): string `MetaString` constructor (returns native string).
---@field NormalCitation CitationMode
---@field Note fun(content: BlocksLike): Note `Note` constructor.
---@field OneParen ListNumberDelim
---@field OrderedList fun(items: List<BlocksLike>|BlocksLike[], listAttributes?: ListAttributes): OrderedList `OrderedList` constructor.
---@field Pandoc fun(blocks: BlocksLike, meta?: Meta): Pandoc Pandoc document constructor.
---@field Para fun(content: InlinesLike|Inline[]): Para `Para` constructor.
---@field path PandocPathModule
---@field Period ListNumberDelim
---@field pipe fun(command: string, args: string[], input: string): string Runs command with the given arguments, passing it the given input, and returns the output as a string. Raises a Lua error if the command exits with a non-zero status (confirmed via testing: the error is not returned as a normal value, so wrap calls in `pcall` to handle failures gracefully).
---@field Plain fun(content: InlinesLike|Inline[]): Plain `Plain` constructor.
---@field Quoted fun(quotetype: QuoteType, content: InlinesLike): Quoted `Quoted` constructor.
---@field RawBlock fun(format: string, text: string): RawBlock `RawBlock` constructor.
---@field RawInline fun(format: string, text: string): RawInline `RawInline` constructor.
---@field read fun(markup: string|Source[], format?: string|FormatTable, reader_options?: ReaderOptions): Pandoc Parse the given string into a Pandoc document.
---@field ReaderOptions fun(opts: ReaderOptions): ReaderOptions `ReaderOptions` constructor.
---@field readers table<string,boolean> Set of formats that pandoc can parse. All keys in this table can be used as the `format` value in `pandoc.read`.
---@field Row fun(cells?: List<Cell>|Cell[], attr?: Attr): Row `Table` row constructor. Both parameters are optional.
---@field scaffolding PandocScaffoldingModule
---@field sha1 fun(input: string): string Computes the SHA1 hash of the given string input.
---@field SimpleTable fun(caption: Caption, aligns: List<Alignment>|Alignment[], widths: List<number>|number[], headers: List<BlocksLike>|BlocksLike[], rows: List<List<BlocksLike>|BlocksLike[]>): SimpleTable `SimpleTable` (pre Pandoc 2.10) constructor.
---@field SingleQuote QuoteType
---@field SmallCaps fun(content: InlinesLike): SmallCaps `SmallCaps` constructor.
---@field SoftBreak fun(): SoftBreak `SoftBreak` constructor.
---@field Space fun(): Space `Space` constructor.
---@field Span fun(content: InlinesLike|Inline[], attr?: Attr): Span `Span` constructor.
---@field Str fun(text: string): Str `Str` constructor.
---@field Strikeout fun(content: InlinesLike): Strikeout `Strikeout` constructor.
---@field Strong fun(content: InlinesLike): Strong `Strong` constructor.
---@field structure PandocStructureModule
---@field Subscript fun(content: InlinesLike): Subscript `Subscript` constructor.
---@field Superscript fun(content: InlinesLike): Superscript `Superscript` constructor.
---@field SuppressAuthor CitationMode
---@field system PandocSystemModule
---@field Table fun(caption: Caption, colspecs: List<ColSpec>|ColSpec[], head: TableHead, bodies: List<TableBody>|TableBody[], foot: TableFoot, attr?: Attr): Table `Table` constructor.
---@field TableBody fun(body?: List<Row>|Row[], head?: List<Row>|Row[], row_head_columns?: integer, attr?: Attr): TableBody `TableBody` constructor. The FIRST positional argument is the body rows, the second the intermediate-head rows nested inside this body. Verified against pandoc 3.11: `pandoc.TableBody(List{A}, List{B}, 0)` yields `.body[1] == A` and `.head[1] == B`. Prefer positional arguments for `TableHead`/`TableBody`/`TableFoot`/`Row`/`Cell` -- a single keyword table is not reliable for every field (`TableHead{rows = ...}` silently produces an empty head).
---@field TableFoot fun(rows?: List<Row>|Row[], attr?: Attr): TableFoot `TableFoot` constructor.
---@field TableHead fun(rows?: List<Row>|Row[], attr?: Attr): TableHead `TableHead` constructor. NOTE: prefer positional args; `pandoc.TableHead{rows = {...}}` has been observed to silently drop the rows.
---@field template PandocTemplateModule
---@field text PandocTextModule
---@field TwoParens ListNumberDelim
---@field types PandocTypesModule
---@field Underline fun(content: InlinesLike): Underline `Underline` constructor.
---@field UpperAlpha ListNumberStyle
---@field UpperRoman ListNumberStyle
---@field utils PandocUtilsModule
---@field walk_block fun(element: Block, filter: Filter): BlockFilterResult
---@field walk_inline fun(element: Inline, filter: Filter): InlineFilterResult
---@field write fun(doc: Pandoc, format?:string|FormatTable, writer_options?: WriterOptions): string Converts a document to the given target format.
---@field write_classic fun(doc: Pandoc, writer_options?: WriterOptions): string Runs a classic custom Lua writer, using the functions defined in the current environment.
---@field WriterOptions fun(opts: WriterOptions): WriterOptions `WriterOptions` constructor.
---@field writers table<string,boolean> Set of formats that pandoc can generate. All keys in this table can be used as the `format` value in `pandoc.write`.
---@field zip PandocZipModule

---@class FormatTable Used as eventual second argument of `pandoc.read`.
---@field format string
---@field extensions table<string,ExtensionState>
